package completion

import (
	"context"
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/peterbourgon/ff/v3/ffcli"
)

// Command returns the completion command. It requires the root command
// to walk the command tree, so it must be wired after root is created.
// Use SetRoot to provide the root command before execution.
func Command() *ffcli.Command {
	return &ffcli.Command{
		Name:       "completion",
		ShortUsage: "aads completion <bash|zsh|fish>",
		ShortHelp:  "Generate shell completion scripts.",
		LongHelp: `Supported shells: bash, zsh, fish.

To load completions:

  Bash:
    source <(aads completion bash)
    # or add to ~/.bashrc:
    eval "$(aads completion bash)"

  Zsh:
    source <(aads completion zsh)
    # or save to fpath:
    aads completion zsh > "${fpath[1]}/_aads"

  Fish:
    aads completion fish | source
    # or save permanently:
    aads completion fish > ~/.config/fish/completions/aads.fish`,
		FlagSet: flag.NewFlagSet("completion", flag.ContinueOnError),
		Exec: func(ctx context.Context, args []string) error {
			if len(args) != 1 {
				return flag.ErrHelp
			}

			root := rootCmd
			if root == nil {
				return fmt.Errorf("completion: root command not set")
			}

			switch strings.ToLower(args[0]) {
			case "bash":
				generateBash(root)
			case "zsh":
				generateZsh(root)
			case "fish":
				generateFish(root)
			default:
				return fmt.Errorf("unsupported shell %q: use bash, zsh, or fish", args[0])
			}
			return nil
		},
	}
}

var rootCmd *ffcli.Command

// SetRoot provides the root command for completion generation.
func SetRoot(root *ffcli.Command) {
	rootCmd = root
}

// commandInfo holds the extracted name and flags of a command.
type commandInfo struct {
	fullName string   // e.g. "campaigns list"
	flags    []string // e.g. ["--campaign-id", "--limit"]
}

// walkCommands recursively collects all commands and their flags.
func walkCommands(cmd *ffcli.Command, prefix string) []commandInfo {
	var result []commandInfo
	for _, sub := range cmd.Subcommands {
		name := sub.Name
		full := name
		if prefix != "" {
			full = prefix + " " + name
		}

		var flags []string
		if sub.FlagSet != nil {
			seen := make(map[string]bool)
			sub.FlagSet.VisitAll(func(f *flag.Flag) {
				if !seen[f.Name] {
					seen[f.Name] = true
					flags = append(flags, "--"+f.Name)
				}
			})
			sort.Strings(flags)
		}

		result = append(result, commandInfo{fullName: full, flags: flags})
		result = append(result, walkCommands(sub, full)...)
	}
	return result
}

// subcommandNames returns the direct subcommand names of a command.
func subcommandNames(cmd *ffcli.Command) []string {
	var names []string
	for _, sub := range cmd.Subcommands {
		names = append(names, sub.Name)
	}
	return names
}

func generateBash(root *ffcli.Command) {
	cmds := walkCommands(root, "")

	// Build lookup: "campaigns" -> ["list", "get", "create", ...]
	subMap := make(map[string][]string) // parent full name -> child names
	flagMap := make(map[string][]string)

	// Root subcommands
	subMap[""] = subcommandNames(root)

	for _, sub := range root.Subcommands {
		subMap[sub.Name] = subcommandNames(sub)
	}

	for _, ci := range cmds {
		flagMap[ci.fullName] = ci.flags
	}

	// Also collect root flags
	var rootFlags []string
	if root.FlagSet != nil {
		root.FlagSet.VisitAll(func(f *flag.Flag) {
			rootFlags = append(rootFlags, "--"+f.Name)
		})
	}

	fmt.Fprintln(os.Stdout, `# bash completion for aads
# Generated by: aads completion bash

_aads() {
    local cur prev words cword
    _init_completion || return

    # Find the subcommand position
    local cmd=""
    local subcmd=""
    local i=1
    while [[ $i -lt $cword ]]; do
        local w="${words[$i]}"
        if [[ "$w" != -* ]]; then
            if [[ -z "$cmd" ]]; then
                cmd="$w"
            elif [[ -z "$subcmd" ]]; then
                subcmd="$w"
            fi
        fi
        ((i++))
    done`)

	// Root level
	fmt.Fprintf(os.Stdout, `
    if [[ -z "$cmd" ]]; then
        if [[ "$cur" == -* ]]; then
            COMPREPLY=($(compgen -W "%s" -- "$cur"))
        else
            COMPREPLY=($(compgen -W "%s" -- "$cur"))
        fi
        return
    fi
`, strings.Join(rootFlags, " "), strings.Join(subMap[""], " "))

	// Command level: generate case statements
	fmt.Fprintln(os.Stdout, `    case "$cmd" in`)
	for _, groupCmd := range root.Subcommands {
		name := groupCmd.Name
		subs := subcommandNames(groupCmd)
		var groupFlags []string
		if groupCmd.FlagSet != nil {
			groupCmd.FlagSet.VisitAll(func(f *flag.Flag) {
				groupFlags = append(groupFlags, "--"+f.Name)
			})
		}

		fmt.Fprintf(os.Stdout, "        %s)\n", name)
		if len(subs) > 0 {
			fmt.Fprintf(os.Stdout, `            if [[ -z "$subcmd" ]]; then
                if [[ "$cur" == -* ]]; then
                    COMPREPLY=($(compgen -W "%s" -- "$cur"))
                else
                    COMPREPLY=($(compgen -W "%s" -- "$cur"))
                fi
                return
            fi
`, strings.Join(groupFlags, " "), strings.Join(subs, " "))

			// Sub-subcommand flags
			fmt.Fprintln(os.Stdout, `            case "$subcmd" in`)
			for _, sub := range groupCmd.Subcommands {
				flags := flagMap[name+" "+sub.Name]
				if len(flags) > 0 {
					fmt.Fprintf(os.Stdout, "                %s)\n", sub.Name)
					fmt.Fprintf(os.Stdout, `                    COMPREPLY=($(compgen -W "%s" -- "$cur"))
                    ;;
`, strings.Join(flags, " "))
				}
			}
			fmt.Fprintln(os.Stdout, `            esac`)
		} else if len(groupFlags) > 0 {
			fmt.Fprintf(os.Stdout, `            COMPREPLY=($(compgen -W "%s" -- "$cur"))
`, strings.Join(groupFlags, " "))
		}
		fmt.Fprintln(os.Stdout, "            ;;")
	}
	fmt.Fprintln(os.Stdout, `    esac
}

complete -F _aads aads`)
}

func generateZsh(root *ffcli.Command) {
	fmt.Fprintln(os.Stdout, `#compdef aads
# Generated by: aads completion zsh

_aads() {
    local -a commands
    local -a flags

    _arguments -C \
        '1:command:->command' \
        '*::arg:->args'

    case "$state" in
        command)
            commands=(`)

	for _, sub := range root.Subcommands {
		help := strings.ReplaceAll(sub.ShortHelp, "'", "'\\''")
		fmt.Fprintf(os.Stdout, "                '%s:%s'\n", sub.Name, help)
	}

	fmt.Fprintln(os.Stdout, `            )
            _describe 'command' commands
            ;;
        args)
            case "${words[1]}" in`)

	for _, groupCmd := range root.Subcommands {
		subs := groupCmd.Subcommands
		if len(subs) == 0 {
			// Leaf command with flags
			var flags []string
			if groupCmd.FlagSet != nil {
				groupCmd.FlagSet.VisitAll(func(f *flag.Flag) {
					usage := strings.ReplaceAll(f.Usage, "'", "'\\''")
					flags = append(flags, fmt.Sprintf("'--%s[%s]'", f.Name, usage))
				})
			}
			if len(flags) > 0 {
				fmt.Fprintf(os.Stdout, "                %s)\n", groupCmd.Name)
				fmt.Fprintf(os.Stdout, "                    _arguments %s\n", strings.Join(flags, " "))
				fmt.Fprintln(os.Stdout, "                    ;;")
			}
			continue
		}

		fmt.Fprintf(os.Stdout, "                %s)\n", groupCmd.Name)
		fmt.Fprintln(os.Stdout, `                    local -a subcommands
                    _arguments -C \
                        '1:subcommand:->subcommand' \
                        '*::subarg:->subargs'
                    case "$state" in
                        subcommand)
                            subcommands=(`)
		for _, sub := range subs {
			help := strings.ReplaceAll(sub.ShortHelp, "'", "'\\''")
			fmt.Fprintf(os.Stdout, "                                '%s:%s'\n", sub.Name, help)
		}
		fmt.Fprintln(os.Stdout, `                            )
                            _describe 'subcommand' subcommands
                            ;;
                        subargs)
                            case "${words[1]}" in`)
		for _, sub := range subs {
			var flags []string
			if sub.FlagSet != nil {
				sub.FlagSet.VisitAll(func(f *flag.Flag) {
					usage := strings.ReplaceAll(f.Usage, "'", "'\\''")
					flags = append(flags, fmt.Sprintf("'--%s[%s]'", f.Name, usage))
				})
			}
			if len(flags) > 0 {
				fmt.Fprintf(os.Stdout, "                                %s)\n", sub.Name)
				fmt.Fprintf(os.Stdout, "                                    _arguments %s\n", strings.Join(flags, " "))
				fmt.Fprintln(os.Stdout, "                                    ;;")
			}
		}
		fmt.Fprintln(os.Stdout, `                            esac
                            ;;
                    esac
                    ;;`)
	}

	fmt.Fprintln(os.Stdout, `            esac
            ;;
    esac
}

_aads "$@"`)
}

func generateFish(root *ffcli.Command) {
	fmt.Fprintln(os.Stdout, `# fish completion for aads
# Generated by: aads completion fish`)

	// Helper: no subcommand yet
	fmt.Fprintln(os.Stdout, `
# Disable file completion by default
complete -c aads -f`)

	// Root subcommands
	topNames := subcommandNames(root)
	noSubcmdCond := "__fish_use_subcommand"

	for _, sub := range root.Subcommands {
		desc := strings.ReplaceAll(sub.ShortHelp, "'", "\\'")
		fmt.Fprintf(os.Stdout, "complete -c aads -n %s -a %s -d '%s'\n", noSubcmdCond, sub.Name, desc)
	}

	// Root flags
	if root.FlagSet != nil {
		root.FlagSet.VisitAll(func(f *flag.Flag) {
			desc := strings.ReplaceAll(f.Usage, "'", "\\'")
			fmt.Fprintf(os.Stdout, "complete -c aads -n %s -l %s -d '%s'\n", noSubcmdCond, f.Name, desc)
		})
	}

	fmt.Fprintln(os.Stdout)

	// Per-group subcommands and flags
	for _, groupCmd := range root.Subcommands {
		subs := groupCmd.Subcommands
		groupCond := fmt.Sprintf("\"__fish_seen_subcommand_from %s\"", groupCmd.Name)

		// Build condition: seen group command but not any of its subcommands
		if len(subs) > 0 {
			subNames := subcommandNames(groupCmd)
			allOtherTop := make([]string, 0, len(topNames)-1)
			for _, n := range topNames {
				if n != groupCmd.Name {
					allOtherTop = append(allOtherTop, n)
				}
			}
			noSubSub := fmt.Sprintf("\"__fish_seen_subcommand_from %s; and not __fish_seen_subcommand_from %s\"",
				groupCmd.Name, strings.Join(subNames, " "))

			for _, sub := range subs {
				desc := strings.ReplaceAll(sub.ShortHelp, "'", "\\'")
				fmt.Fprintf(os.Stdout, "complete -c aads -n %s -a %s -d '%s'\n", noSubSub, sub.Name, desc)
			}

			// Flags for each subcommand
			for _, sub := range subs {
				if sub.FlagSet == nil {
					continue
				}
				subCond := fmt.Sprintf("\"__fish_seen_subcommand_from %s; and __fish_seen_subcommand_from %s\"",
					groupCmd.Name, sub.Name)
				_ = allOtherTop // suppress unused
				sub.FlagSet.VisitAll(func(f *flag.Flag) {
					desc := strings.ReplaceAll(f.Usage, "'", "\\'")
					fmt.Fprintf(os.Stdout, "complete -c aads -n %s -l %s -d '%s'\n", subCond, f.Name, desc)
				})
			}
		} else {
			// Leaf command (no subcommands) — just flags
			if groupCmd.FlagSet != nil {
				groupCmd.FlagSet.VisitAll(func(f *flag.Flag) {
					desc := strings.ReplaceAll(f.Usage, "'", "\\'")
					fmt.Fprintf(os.Stdout, "complete -c aads -n %s -l %s -d '%s'\n", groupCond, f.Name, desc)
				})
			}
		}
		fmt.Fprintln(os.Stdout)
	}
}
